import type { Metadata } from 'next';

import './globals.css';
import { inter } from './ui/fonts.ts';
import { Header } from './ui/header/index.ts';
import { Footer } from './ui/footer/index.ts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
