import type { Metadata } from 'next';

import '../styles/globals.css';
import { inter } from '../ui/fonts';
import { Footer } from '../ui/footer';
import { Header } from '../ui/header';
import { Toast } from '@/ui/toast';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'GG Stickers!',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0"
        />
      </head>
      <body className={inter.className}>
        <Toast />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
