import type { Metadata } from 'next';

import '../styles/globals.css';
import { inter } from '../ui/fonts';
import { Footer } from '../ui/footer';
import { Header } from '../ui/header';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'GG Stickers!',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
